### ISSUE TITLE
Mettre un target pour la master et le robot

### ISSUE THREAD

**Issue by Gregwar** [NAELIC/firmware-main-board#2]

**Comment by gurvan-ledireach** [comment]
Vous voulez dire quoi par "mettre un target" ?

**Comment by EtienneSchmitz** [comment]
Je te l'ai expliqué hier non?

**Comment by EtienneSchmitz** [comment]
Alban nous a montré, comment faire facilement

**Comment by gurvan-ledireach** [comment]
yep, je sais juste plus c'est quel repository qu'il nous a montré

**Comment by EtienneSchmitz** [comment]
celui de la target (mise sur les pins)
branche platformio, commit je m'en rappele plus !

**Comment by EtienneSchmitz** [comment]
Je m'en occupe !
